import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  safelist: [
    "sm:w-sheet-sm",
    "sm:w-sheet-md",
    "sm:w-sheet-lg",
    "sm:max-w-sheet-sm",
    "sm:max-w-sheet-md",
    "sm:max-w-sheet-lg",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "oklch(var(--border) / <alpha-value>)",
        input: "oklch(var(--input) / <alpha-value>)",
        ring: "oklch(var(--ring) / <alpha-value>)",
        background: "oklch(var(--background) / <alpha-value>)",
        foreground: "oklch(var(--foreground) / <alpha-value>)",
        hierarchy: {
          primary: "oklch(var(--foreground) / var(--foreground-alpha-primary))",
          secondary: "oklch(var(--foreground) / var(--foreground-alpha-secondary))",
          muted: "oklch(var(--foreground) / var(--foreground-alpha-muted))",
          disabled: "oklch(var(--foreground) / var(--foreground-alpha-disabled))",
        },
        overlay: {
          scrim: "var(--overlay-scrim)",
        },
        primary: {
          DEFAULT: "oklch(var(--primary) / <alpha-value>)",
          foreground: "oklch(var(--primary-foreground) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "oklch(var(--secondary) / <alpha-value>)",
          foreground: "oklch(var(--secondary-foreground) / <alpha-value>)",
        },
        destructive: {
          DEFAULT: "oklch(var(--destructive) / <alpha-value>)",
          foreground: "oklch(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "oklch(var(--muted) / <alpha-value>)",
          foreground: "oklch(var(--muted-foreground) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "oklch(var(--accent) / <alpha-value>)",
          foreground: "oklch(var(--accent-foreground) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "oklch(var(--popover) / <alpha-value>)",
          foreground: "oklch(var(--popover-foreground) / <alpha-value>)",
        },
        card: {
          DEFAULT: "oklch(var(--card) / <alpha-value>)",
          foreground: "oklch(var(--card-foreground) / <alpha-value>)",
        },
        "component-labs-score": "oklch(var(--layout-component-labs-score-surface) / <alpha-value>)",
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "oklch(var(--sidebar-foreground) / <alpha-value>)",
          primary: "oklch(var(--sidebar-primary) / <alpha-value>)",
          "primary-foreground": "oklch(var(--sidebar-primary-foreground) / <alpha-value>)",
          accent: "oklch(var(--sidebar-accent) / <alpha-value>)",
          "accent-foreground": "oklch(var(--sidebar-accent-foreground) / <alpha-value>)",
          border: "oklch(var(--sidebar-border) / <alpha-value>)",
          ring: "oklch(var(--sidebar-ring) / <alpha-value>)",
        },
        success: {
          DEFAULT: "oklch(var(--success) / <alpha-value>)",
          foreground: "oklch(var(--success-foreground) / <alpha-value>)",
        },
        warning: {
          DEFAULT: "oklch(var(--warning) / <alpha-value>)",
          foreground: "oklch(var(--warning-foreground) / <alpha-value>)",
        },
        info: {
          DEFAULT: "oklch(var(--info) / <alpha-value>)",
          foreground: "oklch(var(--info-foreground) / <alpha-value>)",
        },
      },
      opacity: {
        100: "var(--alpha-100)",
        4: "var(--alpha-4)",
        7: "var(--alpha-7)",
        12: "var(--alpha-12)",
        20: "var(--alpha-20)",
        30: "var(--alpha-30)",
        40: "var(--alpha-40)",
        50: "var(--alpha-50)",
        75: "var(--alpha-75)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
      },
      spacing: {
        0: "var(--space-0)",
        "0.5": "var(--space-2)",
        "0.75": "var(--space-3)",
        1: "var(--space-4)",
        2: "var(--space-8)",
        3: "var(--space-12)",
        4: "var(--space-16)",
        5: "var(--space-20)",
        6: "var(--space-24)",
        8: "var(--space-32)",
        10: "var(--space-40)",
        20: "var(--space-80)",
        "icon-16": "var(--icon-size-16)",
        "icon-20": "var(--icon-size-20)",
        "icon-24": "var(--icon-size-24)",
        "icon-28": "var(--icon-size-28)",
        "icon-32": "var(--icon-size-32)",
        "icon-40": "var(--icon-size-40)",
        "icon-60": "var(--icon-size-60)",
        "icon-72": "var(--icon-size-72)",
        "model-detail-kpi-x": "var(--layout-model-detail-kpi-x)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      minWidth: {
        "modal-auth": "var(--modal-size-auth)",
      },
      width: {
        "modal-auth": "var(--modal-size-auth)",
        "modal-benchmark-details": "var(--modal-size-benchmark-details)",
        "sheet-sm": "var(--sheet-size-sm)",
        "sheet-md": "var(--sheet-size-md)",
        "sheet-lg": "var(--sheet-size-lg)",
        "sheet-xl": "var(--sheet-size-xl)",
        "icon-16": "var(--icon-size-16)",
        "icon-20": "var(--icon-size-20)",
        "icon-24": "var(--icon-size-24)",
        "icon-28": "var(--icon-size-28)",
        "icon-32": "var(--icon-size-32)",
        "icon-40": "var(--icon-size-40)",
        "icon-60": "var(--icon-size-60)",
        "icon-72": "var(--icon-size-72)",
        "icon-container-104": "var(--icon-container-size-104)",
        "scroll-area": "var(--scroll-area-scrollbar-thickness)",
        avatar: "var(--avatar-size-default)",
        "control-sm": "var(--control-height-sm)",
        "control-md": "var(--control-height-md)",
        "control-lg": "var(--control-height-lg)",
        "component-labs-audit": "var(--layout-component-labs-audit-panel)",
      },
      height: {
        "model-detail-row": "var(--layout-model-detail-row-height)",
        "endpoint-deploy-strip": "var(--layout-endpoint-deploy-strip-height)",
        "icon-16": "var(--icon-size-16)",
        "icon-20": "var(--icon-size-20)",
        "icon-24": "var(--icon-size-24)",
        "icon-28": "var(--icon-size-28)",
        "icon-32": "var(--icon-size-32)",
        "icon-40": "var(--icon-size-40)",
        "icon-60": "var(--icon-size-60)",
        "icon-72": "var(--icon-size-72)",
        "icon-container-104": "var(--icon-container-size-104)",
        "scroll-area": "var(--scroll-area-scrollbar-thickness)",
        avatar: "var(--avatar-size-default)",
        "chart-sm": "var(--chart-height-sm)",
        "chart-md": "var(--chart-height-md)",
        "entry-choice-illustration": "var(--entry-choice-illustration-height)",
        "control-sm": "var(--control-height-sm)",
        "control-md": "var(--control-height-md)",
        "control-lg": "var(--control-height-lg)",
        "components-dropdown": "var(--components-dropdown-max-height)",
        "cosmos-card": "var(--cosmos-card-height)",
        "cosmos-card-basic": "var(--cosmos-card-basic-height)",
      },
      maxWidth: {
        "modal-sm": "var(--modal-size-sm)",
        "modal-md": "var(--modal-size-md)",
        "modal-lg": "var(--modal-size-lg)",
        "modal-auth": "var(--modal-size-auth)",
        "modal-benchmark-details": "var(--modal-size-benchmark-details)",
        "sheet-sm": "var(--sheet-size-sm)",
        "sheet-md": "var(--sheet-size-md)",
        "sheet-lg": "var(--sheet-size-lg)",
        "sheet-xl": "var(--sheet-size-xl)",
        "component-labs": "var(--layout-component-labs-max)",
        "component-labs-row": "var(--layout-component-labs-row-max)",
        "page-intro": "var(--layout-page-intro-max)",
      },
      maxHeight: {
        "components-dropdown": "var(--components-dropdown-max-height)",
        "component-labs-sidebar-mobile": "var(--layout-component-labs-sidebar-mobile-max)",
      },
      minHeight: {
        "benchmark-tile-description": "var(--layout-benchmark-tile-description-min-height)",
        "endpoint-deploy-strip": "var(--layout-endpoint-deploy-strip-height)",
      },
      gridTemplateColumns: {
        "endpoint-review-label": "var(--layout-endpoint-review-label-width) minmax(0, 1fr)",
        "endpoint-deploy-wizard":
          "var(--layout-endpoint-deploy-sidebar-width) minmax(0, 1fr)",
      },
      transitionDuration: {
        200: "var(--motion-duration-200)",
        300: "var(--motion-duration-300)",
        400: "var(--motion-duration-400)",
        500: "var(--motion-duration-500)",
        700: "var(--motion-duration-700)",
        900: "var(--motion-duration-900)",
        1800: "var(--motion-duration-1800)",
        2250: "var(--motion-duration-2250)",
      },
      transitionTimingFunction: {
        standard: "var(--motion-easing-standard)",
      },
      boxShadow: {
        "2xs": "var(--shadow-2xs)",
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        popover: "var(--shadow-popover)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "collapsible-down": {
          from: { height: "0" },
          to: { height: "var(--radix-collapsible-content-height)" },
        },
        "collapsible-up": {
          from: { height: "var(--radix-collapsible-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "progress-indeterminate": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(400%)" },
        },
        "skeleton-shimmer": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(400%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "collapsible-down": "collapsible-down var(--motion-duration-200) var(--motion-easing-standard)",
        "collapsible-up": "collapsible-up var(--motion-duration-200) var(--motion-easing-standard)",
        "caret-blink": "caret-blink var(--motion-duration-900) ease-in-out infinite",
        "progress-indeterminate": "progress-indeterminate var(--motion-duration-2250) linear infinite",
        "skeleton-shimmer": "skeleton-shimmer var(--motion-duration-1800) ease-in-out infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
