/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AppOverviewRouteImport } from './routes/app/overview'
import { Route as AppObserveRouteImport } from './routes/app/observe'
import { Route as AppDeployRouteImport } from './routes/app/deploy'
import { Route as AppCosmosRouteImport } from './routes/app/cosmos'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppEndpointsDeploy_endpointRouteImport } from './routes/app/endpoints.deploy_endpoint'
import { Route as AppEndpointsCreate_endpointRouteImport } from './routes/app/endpoints.create_endpoint'
import { Route as AppEndpointsEndpointIdRouteImport } from './routes/app/endpoints.$endpointId'
import { Route as AppCosmosGuidedRouteImport } from './routes/app/cosmos_.guided'
import { Route as AppCosmosModelIdRouteImport } from './routes/app/cosmos_.$modelId'
import { Route as AppEndpointsEndpointIdDeployRouteImport } from './routes/app/endpoints.$endpointId.deploy'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppObserveRoute = AppObserveRouteImport.update({
  id: '/observe',
  path: '/observe',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeployRoute = AppDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCosmosRoute = AppCosmosRouteImport.update({
  id: '/cosmos',
  path: '/cosmos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEndpointsDeploy_endpointRoute =
  AppEndpointsDeploy_endpointRouteImport.update({
    id: '/endpoints/deploy_endpoint',
    path: '/endpoints/deploy_endpoint',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEndpointsCreate_endpointRoute =
  AppEndpointsCreate_endpointRouteImport.update({
    id: '/endpoints/create_endpoint',
    path: '/endpoints/create_endpoint',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEndpointsEndpointIdRoute = AppEndpointsEndpointIdRouteImport.update({
  id: '/endpoints/$endpointId',
  path: '/endpoints/$endpointId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCosmosGuidedRoute = AppCosmosGuidedRouteImport.update({
  id: '/cosmos_/guided',
  path: '/cosmos/guided',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCosmosModelIdRoute = AppCosmosModelIdRouteImport.update({
  id: '/cosmos_/$modelId',
  path: '/cosmos/$modelId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEndpointsEndpointIdDeployRoute =
  AppEndpointsEndpointIdDeployRouteImport.update({
    id: '/deploy',
    path: '/deploy',
    getParentRoute: () => AppEndpointsEndpointIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/cosmos': typeof AppCosmosRoute
  '/app/deploy': typeof AppDeployRoute
  '/app/observe': typeof AppObserveRoute
  '/app/overview': typeof AppOverviewRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/app/cosmos/$modelId': typeof AppCosmosModelIdRoute
  '/app/cosmos/guided': typeof AppCosmosGuidedRoute
  '/app/endpoints/$endpointId': typeof AppEndpointsEndpointIdRouteWithChildren
  '/app/endpoints/create_endpoint': typeof AppEndpointsCreate_endpointRoute
  '/app/endpoints/deploy_endpoint': typeof AppEndpointsDeploy_endpointRoute
  '/app/endpoints/$endpointId/deploy': typeof AppEndpointsEndpointIdDeployRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/cosmos': typeof AppCosmosRoute
  '/app/deploy': typeof AppDeployRoute
  '/app/observe': typeof AppObserveRoute
  '/app/overview': typeof AppOverviewRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/app/cosmos/$modelId': typeof AppCosmosModelIdRoute
  '/app/cosmos/guided': typeof AppCosmosGuidedRoute
  '/app/endpoints/$endpointId': typeof AppEndpointsEndpointIdRouteWithChildren
  '/app/endpoints/create_endpoint': typeof AppEndpointsCreate_endpointRoute
  '/app/endpoints/deploy_endpoint': typeof AppEndpointsDeploy_endpointRoute
  '/app/endpoints/$endpointId/deploy': typeof AppEndpointsEndpointIdDeployRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/cosmos': typeof AppCosmosRoute
  '/app/deploy': typeof AppDeployRoute
  '/app/observe': typeof AppObserveRoute
  '/app/overview': typeof AppOverviewRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/app/cosmos_/$modelId': typeof AppCosmosModelIdRoute
  '/app/cosmos_/guided': typeof AppCosmosGuidedRoute
  '/app/endpoints/$endpointId': typeof AppEndpointsEndpointIdRouteWithChildren
  '/app/endpoints/create_endpoint': typeof AppEndpointsCreate_endpointRoute
  '/app/endpoints/deploy_endpoint': typeof AppEndpointsDeploy_endpointRoute
  '/app/endpoints/$endpointId/deploy': typeof AppEndpointsEndpointIdDeployRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/account'
    | '/app/cosmos'
    | '/app/deploy'
    | '/app/observe'
    | '/app/overview'
    | '/auth/set-password'
    | '/app/cosmos/$modelId'
    | '/app/cosmos/guided'
    | '/app/endpoints/$endpointId'
    | '/app/endpoints/create_endpoint'
    | '/app/endpoints/deploy_endpoint'
    | '/app/endpoints/$endpointId/deploy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/account'
    | '/app/cosmos'
    | '/app/deploy'
    | '/app/observe'
    | '/app/overview'
    | '/auth/set-password'
    | '/app/cosmos/$modelId'
    | '/app/cosmos/guided'
    | '/app/endpoints/$endpointId'
    | '/app/endpoints/create_endpoint'
    | '/app/endpoints/deploy_endpoint'
    | '/app/endpoints/$endpointId/deploy'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/account'
    | '/app/cosmos'
    | '/app/deploy'
    | '/app/observe'
    | '/app/overview'
    | '/auth/set-password'
    | '/app/cosmos_/$modelId'
    | '/app/cosmos_/guided'
    | '/app/endpoints/$endpointId'
    | '/app/endpoints/create_endpoint'
    | '/app/endpoints/deploy_endpoint'
    | '/app/endpoints/$endpointId/deploy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/observe': {
      id: '/app/observe'
      path: '/observe'
      fullPath: '/app/observe'
      preLoaderRoute: typeof AppObserveRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/deploy': {
      id: '/app/deploy'
      path: '/deploy'
      fullPath: '/app/deploy'
      preLoaderRoute: typeof AppDeployRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cosmos': {
      id: '/app/cosmos'
      path: '/cosmos'
      fullPath: '/app/cosmos'
      preLoaderRoute: typeof AppCosmosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/endpoints/deploy_endpoint': {
      id: '/app/endpoints/deploy_endpoint'
      path: '/endpoints/deploy_endpoint'
      fullPath: '/app/endpoints/deploy_endpoint'
      preLoaderRoute: typeof AppEndpointsDeploy_endpointRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/endpoints/create_endpoint': {
      id: '/app/endpoints/create_endpoint'
      path: '/endpoints/create_endpoint'
      fullPath: '/app/endpoints/create_endpoint'
      preLoaderRoute: typeof AppEndpointsCreate_endpointRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/endpoints/$endpointId': {
      id: '/app/endpoints/$endpointId'
      path: '/endpoints/$endpointId'
      fullPath: '/app/endpoints/$endpointId'
      preLoaderRoute: typeof AppEndpointsEndpointIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cosmos_/guided': {
      id: '/app/cosmos_/guided'
      path: '/cosmos/guided'
      fullPath: '/app/cosmos/guided'
      preLoaderRoute: typeof AppCosmosGuidedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cosmos_/$modelId': {
      id: '/app/cosmos_/$modelId'
      path: '/cosmos/$modelId'
      fullPath: '/app/cosmos/$modelId'
      preLoaderRoute: typeof AppCosmosModelIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/endpoints/$endpointId/deploy': {
      id: '/app/endpoints/$endpointId/deploy'
      path: '/deploy'
      fullPath: '/app/endpoints/$endpointId/deploy'
      preLoaderRoute: typeof AppEndpointsEndpointIdDeployRouteImport
      parentRoute: typeof AppEndpointsEndpointIdRoute
    }
  }
}

interface AppEndpointsEndpointIdRouteChildren {
  AppEndpointsEndpointIdDeployRoute: typeof AppEndpointsEndpointIdDeployRoute
}

const AppEndpointsEndpointIdRouteChildren: AppEndpointsEndpointIdRouteChildren =
  {
    AppEndpointsEndpointIdDeployRoute: AppEndpointsEndpointIdDeployRoute,
  }

const AppEndpointsEndpointIdRouteWithChildren =
  AppEndpointsEndpointIdRoute._addFileChildren(
    AppEndpointsEndpointIdRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCosmosRoute: typeof AppCosmosRoute
  AppDeployRoute: typeof AppDeployRoute
  AppObserveRoute: typeof AppObserveRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppCosmosModelIdRoute: typeof AppCosmosModelIdRoute
  AppCosmosGuidedRoute: typeof AppCosmosGuidedRoute
  AppEndpointsEndpointIdRoute: typeof AppEndpointsEndpointIdRouteWithChildren
  AppEndpointsCreate_endpointRoute: typeof AppEndpointsCreate_endpointRoute
  AppEndpointsDeploy_endpointRoute: typeof AppEndpointsDeploy_endpointRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCosmosRoute: AppCosmosRoute,
  AppDeployRoute: AppDeployRoute,
  AppObserveRoute: AppObserveRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppCosmosModelIdRoute: AppCosmosModelIdRoute,
  AppCosmosGuidedRoute: AppCosmosGuidedRoute,
  AppEndpointsEndpointIdRoute: AppEndpointsEndpointIdRouteWithChildren,
  AppEndpointsCreate_endpointRoute: AppEndpointsCreate_endpointRoute,
  AppEndpointsDeploy_endpointRoute: AppEndpointsDeploy_endpointRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
